jobs:
- job: build_geoip
  timeoutInMinutes: 30

  pool:
    vmImage: 'ubuntu-16.04'

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: self
  - task: GoTool@0
    inputs:
      version: '1.11.2'
  - script: |
      go version
      chmod +x $(Build.SourcesDirectory)/generate.sh
      $(Build.SourcesDirectory)/generate.sh
      ls -al ./publish/
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Generate'
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(system.defaultworkingdirectory)/publish'
      contents: 'geoip.dat'
      targetFolder: '$(build.artifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
